{
  "swagger": "2.0",
  "info": {
    "description": "This is API Documentation.",
    "version": "1.0.0",
    "title": "Express Auth",
    "contact": {
      "email": "wlmchrstn@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "basePath": "/api",
  "tags": [
    {
      "name": "User Operation",
      "description": "Operations about user",
      "externalDocs": {
        "description": "Find out more about our store",
        "url": "http://swagger.io"
      }
    }
  ],
  "schemes": [
    "http",
    "https"
  ],
  "paths": {
    "/user/create": {
      "post": {
        "tags": [
          "User Operation"
        ],
        "summary": "Register User",
        "description": "Regiter an user",
        "operationId": "addUser",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Users that will be registered on database",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserRegister"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User created!",
            "schema": {
              "$ref":"#/definitions/UserCreated"
            }
          },
          "422": {
              "description": "Username already taken!",
              "schema": 
                {
                  "$ref":"#/definitions/UsernameTaken"
                }
          },
          "x-422": {
              "description": "Email already taken!",
              "schema": {
                "$ref":"#/definitions/EmailTaken"
              }
          },
          "423": {
              "description": "Failed to create user!",
              "schema": {
                "$ref":"#/definitions/FailedRegister"
              }
          }
        }
      }
    },
    "/user/login": {
      "post": {
        "tags": [
          "User Operation"
        ],
        "summary": "Login User",
        "description": "Login to registered user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Will post username and password to database and database will check if it's true or not.",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserLogin"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Token created!",
            "schema": {
              "$ref":"#/definitions/TokenCreated"
            }
          },
          "403": {
            "description": "Password incorrect!",
            "schema": {
              "$ref":"#/definitions/PasswordIncorrect"
            }
          },
          "404": {
            "description": "Invalid username!",
            "schema": {
              "$ref":"#/definitions/NotFound"
            }
          },
          "422": {
            "description": "Failed to login!",
            "schema": {
              "$ref":"#/definitions/FailedLogin"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/user/info": {
      "get": {
        "tags": [
          "User Operation"
        ],
        "summary": "Show User",
        "description": "Get user detail information if access granted!.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "User detail!",
            "schema": {
              "$ref":"#/definitions/UserDetail"
            }
          },
          "401": {
            "description": "No token!",
            "schema": {
              "$ref":"#/definitions/NoToken"
            }
          },
          "403": {
            "description": "Invalid token!",
            "schema": {
              "$ref":"#/definitions/InvalidToken"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/profile/create": {
      "post": {
        "tags": [
          "Profile Operation"
        ],
        "summary": "Create User Profile",
        "description": "Create current user profile",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Will create current user profile.",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateProfile"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Profile created!",
            "schema": {
              "$ref":"#/definitions/MerchantCreated"
            }
          },
          "x-201": {
            "description": "Profile created!",
            "schema": {
              "$ref":"#/definitions/BuyerCreated"
            }
          },
          "422": {
            "description": "Failed to create profile!",
            "schema": {
              "$ref":"#/definitions/FailedProfile"
            }
          },
          "400": {
            "description": "Bad request!",
            "schema": {
              "$ref":"#/definitions/BadRequest"
            }
          },
          "409": {
            "description": "Profile already created!",
            "schema": {
              "$ref":"#/definitions/ProfileAlready"
            }
          },
          "401": {
            "description": "No token!",
            "schema": {
              "$ref":"#/definitions/NoToken"
            }
          },
          "403": {
            "description": "Invalid token!",
            "schema": {
              "$ref":"#/definitions/InvalidToken"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/profile/update": {
      "put": {
        "tags": [
          "Profile Operation"
        ],
        "summary": "Update User Profile",
        "description": "Update current user profile",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Will update current user profile.",
            "required": true,
            "schema": {
              "$ref": "#/definitions/EditProfile"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Profile updated!",
            "schema": {
              "$ref":"#/definitions/MerchantUpdated"
            }
          },
          "x-200": {
            "description": "Profile updated!",
            "schema": {
              "$ref":"#/definitions/BuyerUpdated"
            }
          },
          "422": {
            "description": "Failed to update profile",
            "schema": {
              "$ref":"#/definitions/FailedProfileUpdate"
            }
          },
          "x-422":{
            "description":"Unexpected error! Please create profile first!",
            "schema":{
              "$ref":"#/definitions/CreateProfileFirst"
            }
          },
          "400": {
            "description": "Name can't be blank!",
            "schema": {
              "$ref":"#/definitions/BlankName"
            }
          },
          "401": {
            "description": "No token!",
            "schema": {
              "$ref":"#/definitions/NoToken"
            }
          },
          "403": {
            "description": "Invalid token!",
            "schema": {
              "$ref":"#/definitions/InvalidToken"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/profile/show/{id}": {
      "get": {
        "tags": [
          "Profile Operation"
        ],
        "summary": "Get User Profile Detail",
        "description": "Get user profile detail",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "Insert profile id here!",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
              "description": "Merchant profile",
              "schema": {
                "$ref":"#/definitions/MerchantCreated"
              }
          },
          "x-200": {
              "description": "Buyer profile",
              "schema": {
                "schema": {
                  "$ref":"#/definitions/BuyerCreated"
                }
              }
          },
          "404": {
            "description": "Profile not found!",
            "schema": {
              "$ref":"#/definitions/ProfileNotFound"
            }
          }
        }
      }
    },
    "/product/create": {
      "post": {
        "tags":[
          "Product Operation"
        ],
        "summary":"Create Product",
        "description":"Create current Merchant product",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
          {
            "in":"body",
            "name":"body",
            "description":"Will create current Merchant product",
            "required":true,
            "schema": {
              "$ref":"#/definitions/CreateProduct"
            }
          }
        ],
        "responses": {
          "201": {
            "description":"Product created!",
            "schema":{
              "$ref":"#/definitions/ProductCreated"
            }
          },
          "400": {
            "description":"Bad request!",
            "schema": {
              "$ref":"#/definitions/BadRequestProduct"
            }
          },
          "422":{
            "description":"Failed to create product!",
            "schema":{
              "$ref":"#/definitions/ProductFailed"
            }
          },
          "x-403":{
            "description":"You are not a Merchant!",
            "schema":{
              "$ref":"#/definitions/NotMerchant"
            }
          },
          "401": {
            "description": "No token!",
            "schema": {
              "$ref":"#/definitions/NoToken"
            }
          },
          "403": {
            "description": "Invalid token!",
            "schema": {
              "$ref":"#/definitions/InvalidToken"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/upload/{id}": {
      "post":{
        "tags":[
          "Product Operation"
        ],
        "parameters":[
          {
            "in":"path",
            "name":"id",
            "required":true,
            "description":"Insert product id here!",
            "type":"string"
          },
          {
            "in":"formData",
            "name":"preview",
            "required":true,
            "description":"Insert the picture here!",
            "type":"file"
          }
        ],
        "summary":"Upload product preview",
        "description":"Upload product preview",
        "consumes":[
          "multipart/form-data"
        ],
        "produces":[
          "application/json"
        ],
        "responses":{
          "200":{
            "description":"Picture uploaded!",
            "schema":{
              "$ref":"#/definitions/Uploaded"
            }
          },
          "422":{
            "description":"Unexpected error! Failed to upload picture!",
            "schema":{
              "$ref":"#/definitions/FailedUpload"
            }
          }
        }
      }
    },
    "/product/list": {
      "get": {
        "tags":[
          "Product Operation"
        ],
        "summary":"Get All Product",
        "description":"Get all Merchant's product",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
        ],
        "responses": {
          "200": {
            "description":"Here is the list!",
            "schema": {
              "$ref":"#/definitions/AllProduct"
            }
          },
          "404": {
            "description":"Product not found!",
            "schema": {
              "$ref":"#/definitions/NoProduct"
            }
          }
        }
      }
    },
    "/product/search": {
      "get": {
        "tags":[
          "Product Operation"
        ],
        "summary":"Search Product",
        "description":"Search Merchant's product",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
          {
            "in": "query",
            "name": "name",
            "type":"string"
          },
          {
            "in": "query",
            "name": "price",
            "type":"number"
          },
          {
            "in": "query",
            "name": "stock",
            "type":"number"
          }
        ],
        "responses": {
          "200": {
            "description":"Here is the list!",
            "schema": {
              "$ref":"#/definitions/AllProduct"
            }
          },
          "404": {
            "description":"Product not found!",
            "schema": {
              "$ref":"#/definitions/NoProduct"
            }
          }
        }
      }
    },
    "/product/detail/{id}": {
      "get": {
        "tags":[
          "Product Operation"
        ],
        "summary":"Get Product Detail",
        "description":"Get product detail",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
          {
            "in":"path",
            "name":"id",
            "description":"Insert product id here!",
            "required":true,
            "type":"string"
          }
        ],
        "responses": {
          "200": {
            "description":"Here is the detail!",
            "schema": {
              "$ref":"#/definitions/DetailProduct"
            }
          },
          "404": {
            "description":"Product not found!",
            "schema": {
              "$ref":"#/definitions/NoProduct"
            }
          }
        }
      }
    },
    "/product/update/{id}": {
      "put": {
        "tags":[
          "Product Operation"
        ],
        "summary":"Update Product",
        "description":"Update current Merchant product",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
          {
            "in":"path",
            "name":"id",
            "description":"Insert product id here!",
            "required":true,
            "type":"string"
          },
          {
            "in":"body",
            "name":"body",
            "description":"Will update product!",
            "required":true,
            "schema": {
              "$ref":"#/definitions/ProductUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description":"Product updated!",
            "schema": {
              "$ref":"#/definitions/UpdatedProduct"
            }
          },
          "400": {
            "description":"Failed to update! Name can't be blank!",
            "schema": {
              "$ref":"#/definitions/BlankNameUpdate"
            }
          },
          "404": {
            "description":"Product not found!",
            "schema": {
              "$ref":"#/definitions/NoProduct"
            }
          },
          "422": {
            "description":"Unexpected error! Failed to update product!",
            "schema":{
              "$ref":"#/definitions/FailedUpdateProduct"
            }
          },
          "401": {
            "description": "No token!",
            "schema": {
              "$ref":"#/definitions/NoToken"
            }
          },
          "403": {
            "description": "Invalid token!",
            "schema": {
              "$ref":"#/definitions/InvalidToken"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/product/delete/{id}": {
      "delete": {
        "tags":[
          "Product Operation"
        ],
        "summary":"Delete Product",
        "description":"Delete current Merchant product",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
          {
            "in":"path",
            "name":"id",
            "description":"Insert product id here!",
            "required":true,
            "type":"string"
          }
        ],
        "responses": {
          "200": {
            "description":"Product deleted!",
            "schema": {
              "$ref":"#/definitions/DeletedProduct"
            }
          },
          "404": {
            "description":"Product not found!",
            "schema": {
              "$ref":"#/definitions/NoProduct"
            }
          },
          "422": {
            "description":"Unexpected error! Failed to delete product!",
            "schema":{
              "$ref":"#/definitions/FailedDeleteProduct"
            }
          },
          "401": {
            "description": "No token!",
            "schema": {
              "$ref":"#/definitions/NoToken"
            }
          },
          "403": {
            "description": "Invalid token!",
            "schema": {
              "$ref":"#/definitions/InvalidToken"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/order/create": {
      "post": {
        "tags":[
          "Order Operation"
        ],
        "summary":"Create Order",
        "description":"Create Buyer order",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
        ],
        "responses": {
          "201": {
            "description":"Order created!",
            "schema":{
              "$ref":"#/definitions/OrderCreated"
            }
          },
          "400": {
            "description":"Bad request!",
            "schema": {
              "$ref":"#/definitions/BadRequestOrder"
            }
          },
          "422":{
            "description":"Failed to create order!",
            "schema":{
              "$ref":"#/definitions/OrderFailed"
            }
          },
          "x-403":{
            "description":"You are not a Buyer!",
            "schema":{
              "$ref":"#/definitions/NotBuyer"
            }
          },
          "401": {
            "description": "No token!",
            "schema": {
              "$ref":"#/definitions/NoToken"
            }
          },
          "403": {
            "description": "Invalid token!",
            "schema": {
              "$ref":"#/definitions/InvalidToken"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/order/delete/{id}": {
      "get": {
        "tags":[
          "Order Operation"
        ],
        "summary":"Delete Order",
        "description":"Delete order",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
          {
            "in":"path",
            "name":"id",
            "description":"Insert order id here!",
            "required":true,
            "type":"string"
          }
        ],
        "responses": {
          "200": {
            "description":"Order deleted!",
            "schema": {
              "$ref":"#/definitions/DeletedOrder"
            }
          },
          "404": {
            "description":"Order not found!",
            "schema": {
              "$ref":"#/definitions/NoOrder"
            }
          },
          "422": {
            "description":"Unexpected error! Failed to delete order!",
            "schema":{
              "$ref":"#/definitions/FailedDeleteOrder"
            }
          },
          "x-403": {
            "description":"This is not your order!",
            "schema":{
              "$ref":"#/definitions/NotOrderOwner"
            }
          },
          "401": {
            "description": "No token!",
            "schema": {
              "$ref":"#/definitions/NoToken"
            }
          },
          "403": {
            "description": "Invalid token!",
            "schema": {
              "$ref":"#/definitions/InvalidToken"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/order/detail/{id}": {
      "post": {
        "tags":[
          "Order Operation"
        ],
        "summary":"Get Order Detail",
        "description":"Get order detail",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
          {
            "in":"path",
            "name":"id",
            "description":"Insert order id here!",
            "required":true,
            "type":"string"
          }
        ],
        "responses": {
          "200": {
            "description":"Here is the detail!",
            "schema": {
              "$ref":"#/definitions/GetOrder"
            }
          },
          "x-403": {
            "description":"This is not your order!!",
            "schema":{
              "$ref":"#/definitions/NotOrderOwner"
            }
          },
          "422": {
            "description":"Unexpected error! Failed to get order!",
            "schema": {
              "$ref":"#/definitions/FailedGetOrder"
            }
          },
          "401": {
            "description": "No token!",
            "schema": {
              "$ref":"#/definitions/NoToken"
            }
          },
          "403": {
            "description": "Invalid token!",
            "schema": {
              "$ref":"#/definitions/InvalidToken"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/order/add-product/{id}": {
      "post": {
        "tags":[
          "Order Operation"
        ],
        "summary":"Add Product to Order Detail",
        "description":"Add product to order detail",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
          {
            "in":"path",
            "name":"id",
            "description":"Insert order id here!",
            "required":true,
            "type":"string"
          },
          {
            "in":"body",
            "name":"body",
            "description":"Will add product to order!",
            "required":true,
            "schema": {
              "$ref":"#/definitions/addProduct"
            }
          }
        ],
        "responses": {
          "200": {
            "description":"Product added!",
            "schema": {
              "$ref":"#/definitions/AddedProduct"
            }
          },
          "400": {
            "description":"Bad Request!",
            "schema":{
              "$ref":"#/definitions/BadRequestAddProduct"
            }
          },
          "404":{
            "description":"Order not found!",
            "schema":{
              "$ref":"#/definitions/NoOrder"
            }
          },
          "x-404":{
            "description":"Product not found!",
            "schema":{
              "$ref":"#/definitions/NoProduct"
            }
          },
          "x-403":{
            "description":"This is not your order!",
            "schema":{
              "$ref":"#/definitions/NotOrderOwner"
            }
          },
          "422": {
            "description":"Out of stock!",
            "schema":{
              "$ref":"#/definitions/OutOfStock"
            }
          },
          "x-422":{
            "description":"Can't add duplicate product!",
            "schema":{
              "$ref":"#/definitions/NoDupe"
            }
          },
          "423":{
            "description":"Unexpected error! Failed to add product!",
            "schema": {
              "$ref":"#/definitions/FailedAddProduct"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/order/order-detail/{id}": {
      "get": {
        "tags":[
          "Order Operation"
        ],
        "summary":"Get Order Detail",
        "description":"Get order detail",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
          {
            "in":"path",
            "name":"id",
            "description":"Insert detail id here!",
            "required":true,
            "type":"string"
          }
        ],
        "responses": {
          "200": {
            "description":"Here is the detail!",
            "schema":{
              "$ref":"#/definitions/OrderDetail"
            }
          },
          "400": {
            "description":"Bad Request!",
            "schema": {
              "$ref":"#/definitions/BadRequestDetail"
            }
          },
          "422": {
            "description":"Unexpected error! Failed to get order detail!",
            "schema":{
              "$ref":"#/definitions/FailedGetDetail"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/order/update-order-detail/{id}": {
      "put": {
        "tags":[
          "Order Operation"
        ],
        "summary":"Edit Product In Order Detail",
        "description":"Edit product in order detail",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
          {
            "in":"path",
            "name":"id",
            "description":"Insert detail id here!",
            "required":true,
            "type":"string"
          },
          {
            "in":"body",
            "name":"body",
            "description":"Will update product in order detail!",
            "required":true,
            "schema": {
              "$ref":"#/definitions/EditOrderDetail"
            }
          }
        ],
        "responses": {
          "200":{
            "description":"Order updated!",
            "schema":{
              "$ref":"#/definitions/OrderDetailUpdated"
            }
          },
          "400":{
            "description":"Bad Request!",
            "schema":{
              "$ref":"#/definitions/BadRequestUpdateDetail"
            }
          },
          "x-403":{
            "description":"This is not your order!",
            "schema":{
              "$ref":"#/definitions/NotOrderOwner"
            }
          },
          "401": {
            "description": "No token!",
            "schema": {
              "$ref":"#/definitions/NoToken"
            }
          },
          "403": {
            "description": "Invalid token!",
            "schema": {
              "$ref":"#/definitions/InvalidToken"
            }
          },
          "x-422":{
            "description":"Out of stock",
            "schema":{
              "$ref":"#/definitions/OutOfStock"
            }
          },
          "422":{
            "description":"Unexpected error! Failed to update detail!",
            "schema":{
              "$ref":"#/definitions/FailedUpdateDetail"
            }
          },
          "404":{
            "description":"Detail not found!",
            "schema":{
              "$ref":"#/definitions/DetailNotFound"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/order/checkout/{id}": {
      "delete": {
        "tags":[
          "Order Operation"
        ],
        "summary":"Confirm Order",
        "description":"Confirm order and payment",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
          {
            "in":"path",
            "name":"id",
            "description":"Insert order id here!",
            "required":true,
            "type":"string"
          }
        ],
        "responses": {
          "200": {
            "description":"Thank you!",
            "schema":{
              "$ref":"#/definitions/ThankYou"
            }
          },
          "400":{
            "description":"Your cart is empty! Please order something first",
            "schema":{
              "$ref":"#/definitions/EmptyCart"
            }
          },
          "404":{
            "description":"Profile not found!",
            "schema":{
              "$ref":"#/definitions/NoProfile"
            }
          },
          "x-404": {
            "description":"Order not found!",
            "schema": {
              "$ref":"#/definitions/NoOrder"
            }
          },
          "x-403": {
            "description":"This is not your order!",
            "schema":{
              "$ref":"#/definitions/NotOrderOwner"
            }
          },
          "422": {
            "description":"Failed to confirm order",
            "schema":{
              "$ref":"#/definitions/FailedConfirm"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/order/remove-product/{id}": {
      "delete": {
        "tags":[
          "Order Operation"
        ],
        "summary":"Remove Product From Order Detail",
        "description":"Remove product from order detail",
        "consumes":[
          "application/json"
        ],
        "produces":[
          "application/json"
        ],
        "parameters":[
          {
            "in":"path",
            "name":"id",
            "description":"Insert detail id here!",
            "required":true,
            "type":"string"
          }
        ],
        "responses": {
          "200":{
            "description":"Product removed from detail!",
            "schema":{
              "$ref":"#/definitions/RemovedOrder"
            }
          },
          "x-403":{
            "description":"This is not your order!",
            "schema":{
              "$ref":"#/definitions/NotOrderOwner"
            }
          },
          "404":{
            "description":"Order detail not found!",
            "schema":{
              "$ref":"#/definitions/DetailNotFound"
            }
          },
          "422": {
            "description":"Unexpected error! Failed to remove product from detail!",
            "schema":{
              "$ref":"#/definitions/FailedRemoveOrder"
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "Authorization": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "definitions": {
    "UserRegister": {
      "type": "object",
      "required": [
        "username",
        "email",
        "password"
      ],
      "properties": {
        "username": {
          "type": "string",
          "example": "test001"
        },
        "email": {
          "type": "string",
          "example": "test001@mail.com"
        },
        "password": {
          "type": "string",
          "example": "test001"
        }
      }
    },
    "UserCreated": {
      "type": "object",
      "properties": {
        "success": {
          "type":"boolean",
          "example": true
        },
        "message": {
          "type":"string",
          "example":"User created!" 
        },
        "result": {
          "type":"object",
          "example":{
            "_id": "5d7f249df1f14f59f99c7b44",
            "username": "test001",
            "email": "test001@mail.com"
          }
        }        
      }
    },
    "UsernameTaken": {
      "type": "object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"test001 is already taken!"
        }
      }
    },
    "EmailTaken": {
      "type": "object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"test001@mail.com is already registered!" 
        }
      }
    },
    "FailedRegister": {
      "type": "object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Unexpected error! Failed to create user!"
        }
      }
    },
    "UserLogin": {
      "type": "object",
      "required": [
        "username",
        "password"
      ],
      "properties": {
        "username": {
          "type": "string",
          "example": "test001"
        },
        "password": {
          "type": "string",
          "example": "test001"
        }
      }
    },
    "TokenCreated": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example": true
        },
        "result": {
          "type":"object",
          "example":{
            "token": "token"
          }
        },
        "message": {
          "type":"string",
          "example":"Token created!"
        }
      }
    },
    "PasswordIncorrect": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Password incorrect!"
        }
      }
    },
    "NotFound": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"User hasn't registered yet!"
        }
      }
    },
    "FailedLogin": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Unexpected error! Failed to login!"
        }
      }
    },
    "UserDetail": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Here is the details!"
        },
        "result": {
          "type":"object",
          "example":{
            "profiles": [],
            "_id": "id",
            "username": "test001"
          }
        }
      }
    },
    "NoToken": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Please insert token!"
        }
      }
    },
    "InvalidToken": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Invalid token!"
        }
      }
    },
    "CreateProfile": {
      "type": "object",
      "required": [
        "name",
        "role",
        "tags"
      ],
      "properties": {
        "name": {
          "type": "string",
          "example": "Toko test001"
        },
        "role": {
          "type": "string",
          "description":"Choose one!",
          "example": "Merchant/Buyer"
        },
        "tags": {
          "type": "string",
          "example": "Technology"
        }
      }
    },
    "MerchantCreated": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Here is the detail!"
        },
        "result": {
          "type":"object",
          "example":{
            "_id": "id",
            "name": "Toko test001",
            "role": "Merchant",
            "tags": "Technology",
            "products": [],
            "histories": []
          }
        }
      }
    },
    "BuyerCreated": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Here is the detail!"
        },
        "result": {
          "type":"object",
          "example":{
            "_id": "id",
            "name": "Toko test001",
            "role": "Buyer",
            "tags": "Technology",
            "orders": [],
            "histories": []
          }
        }
      }
    },
    "FailedProfile": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Unexpected error! Failed to create profile!"
        }
      }
    },
    "BadRequest": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Bad request! Failed to create profile!"
        }
      }
    },
    "ProfileAlready": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Profile already created!"
        }
      }
    },
    "NoProfile": {
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example": "Profile not found!"
        }
      }
    },
    "EditProfile": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "Toko test001 baru"
        },
        "tags": {
          "type": "string",
          "example": "Fashion"
        }
      }
    },
    "MerchantUpdated": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Profile updated!"
        },
        "result": {
          "type":"object",
          "example":{
            "_id": "id",
            "name": "Toko test001 baru",
            "role": "Merchant",
            "tags": "Fashion",
            "products": []
          }
        }
      }
    },
    "BuyerUpdated": {
      "type":"object",
      "properties": {
        "success": {
          "type":"object",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Profile updated!"
        },
        "result": {
          "type":"object",
          "example":{
            "_id": "id",
            "name": "Toko test001 baru",
            "role": "Buyer",
            "tags": "Fashion",
            "orders": []
          }
        }
      }
    },
    "BlankName": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Failed to updated! Name can't be blank!"
        }
      }
    },
    "FailedProfileUpdate": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Unexpected error! Failed to update profile!"
        }
      }
    },
    "CreateProfileFirst": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Unexpected error! Please create profile first!"
        }
      }
    },
    "ProfileNotFound": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Profile not found!"
        }
      }
    },
    "CreateProduct": {
      "type": "object",
      "required": [
        "name",
        "price",
        "stock"
      ],
      "properties": {
        "name": {
          "type": "string",
          "example": "Laptop"
        },
        "price": {
          "type": "number",
          "example": 5000
        },
        "stock": {
          "type": "number",
          "example": 25
        },
        "description": {
          "type":"string",
          "example":"SPEC i3"
        }
      }
    },
    "ProductCreated": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Product created!"
        },
        "result": {
          "type":"object",
          "example":{
              "_id": "5d808f2296152457eaa4992c",
              "name": "LAPTOP",
              "preview":"http://res.cloudinary.com/wlmchrstn/image/upload/v1568820109/ulilvdvfiwxrvxxzbnmt.jpg",
              "description":"SPEC i3",
              "price": 5000,
              "stock": 25,
              "profiles": "5d808b370a701b4f5090fcb9"
          }
        }
      }
    },
    "BadRequestProduct": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Bad request! Failed to create product!"
        }
      }
    },
    "ProductFailed": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Unexpected error! Failed to create product!"
        }
      }
    },
    "NotMerchant": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Failed to create product! You are not a Merchant!"
        }
      }
    },
    "Uploaded":{
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example":true
        },
        "message":{
          "type":"string",
          "example":"Picture uploaded!"
        },
        "result":{
          "type":"object",
          "example":{
            "_id": "5d81a704b97f37354619cf6c",
            "name": "Kopi",
            "price": 5000,
            "stock": 50,
            "profiles": "5d81a67e0478a73437e0765c",
            "preview": "http://res.cloudinary.com/wlmchrstn/image/upload/v1568820109/ulilvdvfiwxrvxxzbnmt.jpg"
          }
        }
      }
    },
    "FailedUpload":{
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example":false
        },
        "message":{
          "type":"string",
          "example":"Unexpected error! Failed to upload picture!"
        }
      }
    },
    "AllProduct": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Here is the list"
        },
        "result": {
          "type":"object",
          "example": {
                "_id": "5d808f2296152457eaa4992c",
                "description":"SPEC i3",
                "name": "LAPTOP",
                "preview":"http://res.cloudinary.com/wlmchrstn/image/upload/v1568820109/ulilvdvfiwxrvxxzbnmt.jpg",
                "price": 5000,
                "stock": 25
          }
        }
      }
    },
    "DetailProduct": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Here is the detail!"
        },
        "result": {
          "type":"object",
          "example": {
            "_id": "5d808f2296152457eaa4992c",
            "name": "LAPTOP",
            "preview":"http://res.cloudinary.com/wlmchrstn/image/upload/v1568820109/ulilvdvfiwxrvxxzbnmt.jpg",
            "description":"SPEC i3",
            "price": 5000,
            "stock": 25
          }
        }
      }
    },
    "NoProduct": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Product not found!"
        }
      }
    },
    "ProductUpdate": {
      "type": "object",
      "required": [
        "name",
        "price",
        "stock"
      ],
      "properties": {
        "name": {
          "type": "string",
          "example": "PC"
        },
        "description":{
          "type":"string",
          "example":"SPEC i3"
        },
        "price": {
          "type": "number",
          "example": 4000
        },
        "stock": {
          "type": "number",
          "example": 20
        }
      }
    },
    "UpdatedProduct": {
      "type":"object",
      "properties": {
        "success":{
          "type":"boolean",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Product updated!"
        },
        "result": {
          "type":"object",
          "example": {
            "_id": "5d808f2296152457eaa4992c",
            "name": "PC",
            "preview":"http://res.cloudinary.com/wlmchrstn/image/upload/v1568820109/ulilvdvfiwxrvxxzbnmt.jpg",
            "description":"SPEC i3",
            "price": 4000,
            "stock": 20,
            "profiles": "5d808b370a701b4f5q239221w"
          }
        }
      }
    },
    "BlankNameUpdate": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Failed to update! Name can't be blank!"
        }
      }
    },
    "FailedUpdateProduct": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Unexpected error! Failed to update product!"
        }
      }
    },
    "DeletedProduct": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Product deleted!"
        }
      }
    },
    "FailedDeleteProduct": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Unexpected error! Failed to delete product!"
        }
      }
    },
    "OrderCreated": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Order created!"
        },
        "result": {
          "type":"object",
          "example": {
            "total": 0,
            "orderDetails": [],
            "_id": "5d80c2aa319555103fb6d0a2",
            "profiles": "5d80c1516222240f9bd9c4ce"
          }
        }
      }
    },
    "BadRequestOrder": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Bad request! Failed to create order!"
        }
      }
    },
    "OrderFailed": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Unexpected error! Failed to create order!"
        }
      }
    },
    "NotBuyer": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Failed to create order! You are not a Buyer!"
        }
      }
    },
    "DeletedOrder": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Order deleted!"
        }
      }
    },
    "NoOrder": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Order not found!"
        }
      }
    },
    "FailedDeleteOrder": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Unexpected error! Failed to delete order!"
        }
      }
    },
    "NotOrderOwner": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"This is not your order!"
        }
      }
    },
    "GetOrder": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Here is the detail!"
        },
        "result":{
          "type":"object",
          "example":{
            "_id": "id",
            "isDone": false,
            "total": 0,
            "details": "details id"
          }
        }
      }
    },
    "FailedGetOrder":{
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example":false
        },
        "message":{
          "type":"string",
          "example":"Unexpected error! Failed to get order!"
        }
      }
    },
    "addProduct": {
      "type":"object",
      "required":[
        "amount",
        "products"
      ],
      "properties": {
        "amount": {
          "type":"number",
          "example": 3
        },
        "products": {
          "type": "string",
          "example":"5d81a716b97f37354619cf6e"
        }
      }
    },
    "AddedProduct": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":true
        },
        "message": {
          "type":"string",
          "example":"Product added!"
        },
        "result": {
          "type":"object",
          "example": {
            "isDone":false,
            "total":15000,
            "details":"5d81a716b97f37354619cf6e",
            "profiles":"5d80c315942240f9bd9c4ce"
          }
        }
      }
    },
    "BadRequestAddProduct": {
      "type":"object",
      "properties": {
        "success":{
          "type":"boolean",
          "example":false
        },
        "message":{
          "type":"string",
          "example":"Bad request! Amount can't be 0!"
        }
      }
    },
    "OutOfStock": {
      "type":"object",
      "properties": {
        "success":{
          "type":"boolean",
          "example":false
        },
        "message":{
          "type":"string",
          "example":"Out of Stock!"
        }
      }
    },
    "NoDupe": {
      "type":"object",
      "properties": {
        "success":{
          "type":"boolean",
          "example":false
        },
        "message":{
          "type":"string",
          "example":"Can't add duplicate product!!"
        }
      }
    },
    "FailedAddProduct": {
      "type":"object",
      "properties": {
        "success": {
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Unexpected error! Failed to add product!"
        }
      }
    },
    "OrderDetail": {
      "type":"object",
      "properties": {
        "success":{
          "type":"boolean",
          "example":true
        },
        "message":{
          "type":"string",
          "example":"Here is the detail!"
        },
        "result": {
          "type":"object",
          "example": {
            "_id":"5d7f249df1f14f59f99c7b44",
            "products":"5d81a716b97f37354619cf6e",
            "amount":3,
            "subtotal":15000,
            "orders":"5d80c315942240f9bd9c4ce"
          }
        }
      }
    },
    "BadRequestDetail": {
      "type":"object",
      "properties": {
        "success":{
          "type":"boolean",
          "example":false
        },
        "message": {
          "type":"string",
          "example":"Bad request! Failed to get order detail!"
        }
      }
    },
    "FailedGetDetail": {
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example":false
        },
        "message":{
          "type":"string",
          "example":"Unexpected error! Failed to get order detail!"
        }
      }
    },
    "EditOrderDetail": {
      "type":"object",
      "required":[
        "amount"
      ],
      "properties":{
        "amount":{
          "type":"number",
          "example":5
        }
      }
    },
    "OrderDetailUpdated": {
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example":true
        },
        "message":{
          "type":"string",
          "example":"Order updated!"
        },
        "result":{
          "type":"object",
          "example":{
            "_id":"5d7f249df1f14f59f99c7b44",
            "products":"5d81a716b97f37354619cf6e",
            "amount":5,
            "subtotal":25000,
            "orders":"5d80c315942240f9bd9c4ce"
          }
        }
      }
    },
    "BadRequestUpdateDetail": {
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example":false
        },
        "message":{
          "type":"string",
          "example":"Bad request! Failed to update detail!"
        }
      }
    },
    "FailedUpdateDetail": {
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example":false
        },
        "message":{
          "type":"string",
          "example":"Unexpected error! Failed to update detail!"
        }
      }
    },
    "RemovedOrder": {
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example":true
        },
        "message":{
          "type":"string",
          "example":"Product removed from detail!"
        }
      }
    },
    "FailedRemoveOrder": {
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example":false
        },
        "message":{
          "type":"string",
          "example":"Unexpected error! Failed to remove product from detail!"
        }
      }
    },
    "DetailNotFound": {
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example":false
        },
        "message":{
          "type":"string",
          "example":"Order detail not found!"
        }
      }
    },
    "EmptyCart":{
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example":false
        },
        "message":{
          "type":"string",
          "example":"Your cart is empty! Please order something first!"
        }
      }
    },
    "ThankYou": {
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example":true
        },
        "message":{
          "type":"string",
          "example":"Thank you!!"
        }
      }
    },
    "FailedConfirm": {
      "type":"object",
      "properties":{
        "success":{
          "type":"boolean",
          "example":false
        },
        "message":{
          "type":"string",
          "example":"Unexpected error! Failed to confirm order!!"
        }
      }
    }
  },
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "http://swagger.io"
  }
}